version: "3.9"
services:
    web:
        build: ./WebAPI
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
    client:
        build: ./ClientApp
        ports:
            - "8080:8080"
        depends_on:
            - web